name: Build

on:
  workflow_dispatch:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: CMake
        run: cmake --preset-lists

#   build-windows:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Run a one-line script
#         run: echo Hello, world!
#       - name: Run a multi-line script
#         run: |
#           echo Add other actions to build,
#           echo test, and deploy your project.
